/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2021-02-19 10:36:51 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/tmf_app_manager -t action_plugin -t action_queue -t all_permissions -t application -t application_list -t application_response -t application_section -t application_stage_history -t application_stage_status_all -t application_stage_status_latest -t application_status_history -t application_trigger_states -t element_type_plugin -t file -t notification -t organisation -t permission_join -t permission_name -t permission_policy -t review -t review_assignment -t review_decision -t review_question_assignment -t review_response -t review_status_history -t template -t template_action -t template_element -t template_permission -t template_section -t template_stage -t trigger_queue -t user -t user_org_join -t user_organisation -s public
 *
 */

export type action_queue_status = 'Fail' | 'Processing' | 'Queued' | 'Scheduled' | 'Success';
export type application_outcome = 'Approved' | 'Pending' | 'Rejected';
export type application_status = 'Changes Required' | 'Completed' | 'Draft' | 'Expired' | 'Re-submitted' | 'Submitted' | 'Withdrawn';
export type decision = 'Changes Requested' | 'Conform' | 'List of questions' | 'Non-conform';
export type permission_policy_type = 'Apply' | 'Assign' | 'Review';
export type review_assignment_status = 'Assigned' | 'Available' | 'Available for self-assignment' | 'Self-assigned by another';
export type review_response_decision = 'Approve' | 'Decline';
export type review_response_status = 'Draft' | 'Submitted';
export type review_status = 'Changes Requested' | 'Draft' | 'Locked' | 'Pending' | 'Submitted';
export type template_element_category = 'Information' | 'Question';
export type template_status = 'Available' | 'Disabled' | 'Draft';
export type trigger = 'Error' | 'Processing' | 'onApplicationCreate' | 'onApplicationSave' | 'onApplicationSubmit' | 'onApplicationWithdraw' | 'onApprovalSubmit' | 'onReviewAssign' | 'onReviewCreate' | 'onReviewSelfAssign' | 'onReviewStart' | 'onReviewSubmit' | 'onScheduleTime';
export type trigger_queue_status = 'Actions Dispatched' | 'Error' | 'Triggered';

export namespace action_pluginFields {
    export type code = string;
    export type name = string | null;
    export type description = string | null;
    export type path = string | null;
    export type function_name = string | null;
    export type required_parameters = Array<string> | null;
    export type output_properties = Array<string> | null;

}

export interface action_plugin {
    code: action_pluginFields.code;
    name: action_pluginFields.name;
    description: action_pluginFields.description;
    path: action_pluginFields.path;
    function_name: action_pluginFields.function_name;
    required_parameters: action_pluginFields.required_parameters;
    output_properties: action_pluginFields.output_properties;

}

export namespace action_queueFields {
    export type id = number;
    export type trigger_event = number | null;
    export type template_id = number | null;
    export type sequence = number | null;
    export type action_code = string | null;
    export type application_data = Object | null;
    export type parameter_queries = Object | null;
    export type parameters_evaluated = Object | null;
    export type status = action_queue_status | null;
    export type output = Object | null;
    export type time_queued = Date | null;
    export type time_completed = Date | null;
    export type time_scheduled = Date | null;
    export type error_log = string | null;

}

export interface action_queue {
    id: action_queueFields.id;
    trigger_event: action_queueFields.trigger_event;
    template_id: action_queueFields.template_id;
    sequence: action_queueFields.sequence;
    action_code: action_queueFields.action_code;
    application_data: action_queueFields.application_data;
    parameter_queries: action_queueFields.parameter_queries;
    parameters_evaluated: action_queueFields.parameters_evaluated;
    status: action_queueFields.status;
    output: action_queueFields.output;
    time_queued: action_queueFields.time_queued;
    time_completed: action_queueFields.time_completed;
    time_scheduled: action_queueFields.time_scheduled;
    error_log: action_queueFields.error_log;

}

export namespace all_permissionsFields {
    export type permissionType = permission_policy_type | null;
    export type permissionPolicyId = number | null;
    export type permissionPolicyRules = Object | null;
    export type permissionNameId = number | null;
    export type templatePermissionId = number | null;
    export type templatePermissionRestrictions = Object | null;
    export type templateId = number | null;
    export type templateCode = string | null;
    export type userId = number | null;
    export type username = string | null;

}

export interface all_permissions {
    permissionType: all_permissionsFields.permissionType;
    permissionPolicyId: all_permissionsFields.permissionPolicyId;
    permissionPolicyRules: all_permissionsFields.permissionPolicyRules;
    permissionNameId: all_permissionsFields.permissionNameId;
    templatePermissionId: all_permissionsFields.templatePermissionId;
    templatePermissionRestrictions: all_permissionsFields.templatePermissionRestrictions;
    templateId: all_permissionsFields.templateId;
    templateCode: all_permissionsFields.templateCode;
    userId: all_permissionsFields.userId;
    username: all_permissionsFields.username;

}

export namespace applicationFields {
    export type id = number;
    export type template_id = number | null;
    export type user_id = number | null;
    export type org_id = number | null;
    export type serial = string | null;
    export type name = string | null;
    export type outcome = application_outcome | null;
    export type is_active = boolean | null;
    export type trigger = trigger | null;

}

export interface application {
    id: applicationFields.id;
    template_id: applicationFields.template_id;
    user_id: applicationFields.user_id;
    org_id: applicationFields.org_id;
    serial: applicationFields.serial;
    name: applicationFields.name;
    outcome: applicationFields.outcome;
    is_active: applicationFields.is_active;
    trigger: applicationFields.trigger;

}

export namespace application_listFields {
    export type id = number | null;
    export type serial = string | null;
    export type name = string | null;
    export type template_code = string | null;
    export type template_name = string | null;
    export type applicant_username = string | null;
    export type applicant_first_name = string | null;
    export type applicant_last_name = string | null;
    export type applicant = string | null;
    export type org_name = string | null;
    export type stage = string | null;
    export type status = application_status | null;
    export type outcome = application_outcome | null;
    export type last_active_date = Date | null;
    export type is_fully_assigned_level_1 = boolean | null;

}

export interface application_list {
    id: application_listFields.id;
    serial: application_listFields.serial;
    name: application_listFields.name;
    template_code: application_listFields.template_code;
    template_name: application_listFields.template_name;
    applicant_username: application_listFields.applicant_username;
    applicant_first_name: application_listFields.applicant_first_name;
    applicant_last_name: application_listFields.applicant_last_name;
    applicant: application_listFields.applicant;
    org_name: application_listFields.org_name;
    stage: application_listFields.stage;
    status: application_listFields.status;
    outcome: application_listFields.outcome;
    last_active_date: application_listFields.last_active_date;
    is_fully_assigned_level_1: application_listFields.is_fully_assigned_level_1;

}

export namespace application_responseFields {
    export type id = number;
    export type template_element_id = number | null;
    export type application_id = number | null;
    export type value = Object | null;
    export type is_valid = boolean | null;
    export type time_created = Date | null;

}

export interface application_response {
    id: application_responseFields.id;
    template_element_id: application_responseFields.template_element_id;
    application_id: application_responseFields.application_id;
    value: application_responseFields.value;
    is_valid: application_responseFields.is_valid;
    time_created: application_responseFields.time_created;

}

export namespace application_sectionFields {
    export type id = number;
    export type application_id = number | null;
    export type template_section_id = number | null;

}

export interface application_section {
    id: application_sectionFields.id;
    application_id: application_sectionFields.application_id;
    template_section_id: application_sectionFields.template_section_id;

}

export namespace application_stage_historyFields {
    export type id = number;
    export type application_id = number | null;
    export type stage_id = number | null;
    export type time_created = Date | null;
    export type is_current = boolean | null;

}

export interface application_stage_history {
    id: application_stage_historyFields.id;
    application_id: application_stage_historyFields.application_id;
    stage_id: application_stage_historyFields.stage_id;
    time_created: application_stage_historyFields.time_created;
    is_current: application_stage_historyFields.is_current;

}

export namespace application_stage_status_allFields {
    export type application_id = number | null;
    export type template_id = number | null;
    export type serial = string | null;
    export type name = string | null;
    export type user_id = number | null;
    export type org_id = number | null;
    export type stage_id = number | null;
    export type stage_number = number | null;
    export type stage = string | null;
    export type stage_history_id = number | null;
    export type stage_history_time_created = Date | null;
    export type stage_is_current = boolean | null;
    export type status_history_id = number | null;
    export type status = application_status | null;
    export type status_history_time_created = Date | null;
    export type status_is_current = boolean | null;

}

export interface application_stage_status_all {
    application_id: application_stage_status_allFields.application_id;
    template_id: application_stage_status_allFields.template_id;
    serial: application_stage_status_allFields.serial;
    name: application_stage_status_allFields.name;
    user_id: application_stage_status_allFields.user_id;
    org_id: application_stage_status_allFields.org_id;
    stage_id: application_stage_status_allFields.stage_id;
    stage_number: application_stage_status_allFields.stage_number;
    stage: application_stage_status_allFields.stage;
    stage_history_id: application_stage_status_allFields.stage_history_id;
    stage_history_time_created: application_stage_status_allFields.stage_history_time_created;
    stage_is_current: application_stage_status_allFields.stage_is_current;
    status_history_id: application_stage_status_allFields.status_history_id;
    status: application_stage_status_allFields.status;
    status_history_time_created: application_stage_status_allFields.status_history_time_created;
    status_is_current: application_stage_status_allFields.status_is_current;

}

export namespace application_stage_status_latestFields {
    export type application_id = number | null;
    export type template_id = number | null;
    export type serial = string | null;
    export type name = string | null;
    export type user_id = number | null;
    export type org_id = number | null;
    export type stage_id = number | null;
    export type stage_number = number | null;
    export type stage = string | null;
    export type stage_history_id = number | null;
    export type stage_history_time_created = Date | null;
    export type stage_is_current = boolean | null;
    export type status_history_id = number | null;
    export type status = application_status | null;
    export type status_history_time_created = Date | null;
    export type status_is_current = boolean | null;

}

export interface application_stage_status_latest {
    application_id: application_stage_status_latestFields.application_id;
    template_id: application_stage_status_latestFields.template_id;
    serial: application_stage_status_latestFields.serial;
    name: application_stage_status_latestFields.name;
    user_id: application_stage_status_latestFields.user_id;
    org_id: application_stage_status_latestFields.org_id;
    stage_id: application_stage_status_latestFields.stage_id;
    stage_number: application_stage_status_latestFields.stage_number;
    stage: application_stage_status_latestFields.stage;
    stage_history_id: application_stage_status_latestFields.stage_history_id;
    stage_history_time_created: application_stage_status_latestFields.stage_history_time_created;
    stage_is_current: application_stage_status_latestFields.stage_is_current;
    status_history_id: application_stage_status_latestFields.status_history_id;
    status: application_stage_status_latestFields.status;
    status_history_time_created: application_stage_status_latestFields.status_history_time_created;
    status_is_current: application_stage_status_latestFields.status_is_current;

}

export namespace application_status_historyFields {
    export type id = number;
    export type application_stage_history_id = number | null;
    export type status = application_status | null;
    export type time_created = Date | null;
    export type is_current = boolean | null;
    export type application_id = number | null;

}

export interface application_status_history {
    id: application_status_historyFields.id;
    application_stage_history_id: application_status_historyFields.application_stage_history_id;
    status: application_status_historyFields.status;
    time_created: application_status_historyFields.time_created;
    is_current: application_status_historyFields.is_current;
    application_id: application_status_historyFields.application_id;

}

export namespace application_trigger_statesFields {
    export type serial = string | null;
    export type application_id = number | null;
    export type application_trigger = trigger | null;
    export type review_assignment_id = number | null;
    export type review_assignment_trigger = trigger | null;
    export type review_id = number | null;
    export type review_trigger = trigger | null;

}

export interface application_trigger_states {
    serial: application_trigger_statesFields.serial;
    application_id: application_trigger_statesFields.application_id;
    application_trigger: application_trigger_statesFields.application_trigger;
    review_assignment_id: application_trigger_statesFields.review_assignment_id;
    review_assignment_trigger: application_trigger_statesFields.review_assignment_trigger;
    review_id: application_trigger_statesFields.review_id;
    review_trigger: application_trigger_statesFields.review_trigger;

}

export namespace element_type_pluginFields {
    export type code = string;
    export type name = string | null;
    export type description = string | null;
    export type category = template_element_category | null;
    export type path = string | null;
    export type display_component_name = string | null;
    export type config_component_name = string | null;
    export type required_parameters = Array<string> | null;

}

export interface element_type_plugin {
    code: element_type_pluginFields.code;
    name: element_type_pluginFields.name;
    description: element_type_pluginFields.description;
    category: element_type_pluginFields.category;
    path: element_type_pluginFields.path;
    display_component_name: element_type_pluginFields.display_component_name;
    config_component_name: element_type_pluginFields.config_component_name;
    required_parameters: element_type_pluginFields.required_parameters;

}

export namespace fileFields {
    export type id = number;
    export type user_id = number | null;
    export type original_filename = string | null;
    export type path = string | null;
    export type mimetype = string | null;
    export type application_id = number | null;
    export type application_response_id = number | null;

}

export interface file {
    id: fileFields.id;
    user_id: fileFields.user_id;
    original_filename: fileFields.original_filename;
    path: fileFields.path;
    mimetype: fileFields.mimetype;
    application_id: fileFields.application_id;
    application_response_id: fileFields.application_response_id;

}

export namespace notificationFields {
    export type id = number;
    export type user_id = number | null;
    export type application_id = number | null;
    export type review_id = number | null;
    export type subject = string | null;
    export type message = string | null;
    export type document_id = number | null;
    export type is_read = boolean | null;

}

export interface notification {
    id: notificationFields.id;
    user_id: notificationFields.user_id;
    application_id: notificationFields.application_id;
    review_id: notificationFields.review_id;
    subject: notificationFields.subject;
    message: notificationFields.message;
    document_id: notificationFields.document_id;
    is_read: notificationFields.is_read;

}

export namespace organisationFields {
    export type id = number;
    export type name = string | null;
    export type licence_number = string | null;
    export type address = string | null;

}

export interface organisation {
    id: organisationFields.id;
    name: organisationFields.name;
    licence_number: organisationFields.licence_number;
    address: organisationFields.address;

}

export namespace permission_joinFields {
    export type id = number;
    export type user_id = number | null;
    export type organisation_id = number | null;
    export type permission_name_id = number | null;

}

export interface permission_join {
    id: permission_joinFields.id;
    user_id: permission_joinFields.user_id;
    organisation_id: permission_joinFields.organisation_id;
    permission_name_id: permission_joinFields.permission_name_id;

}

export namespace permission_nameFields {
    export type id = number;
    export type name = string | null;
    export type permission_policy_id = number | null;

}

export interface permission_name {
    id: permission_nameFields.id;
    name: permission_nameFields.name;
    permission_policy_id: permission_nameFields.permission_policy_id;

}

export namespace permission_policyFields {
    export type id = number;
    export type name = string | null;
    export type description = string | null;
    export type rules = Object | null;
    export type type = permission_policy_type | null;
    export type default_restrictions = Object | null;

}

export interface permission_policy {
    id: permission_policyFields.id;
    name: permission_policyFields.name;
    description: permission_policyFields.description;
    rules: permission_policyFields.rules;
    type: permission_policyFields.type;
    default_restrictions: permission_policyFields.default_restrictions;

}

export namespace reviewFields {
    export type id = number;
    export type review_assignment_id = number | null;
    export type trigger = trigger | null;
    export type application_id = number | null;
    export type reviewer_id = number | null;
    export type level = number | null;
    export type is_last_level = boolean | null;

}

export interface review {
    id: reviewFields.id;
    review_assignment_id: reviewFields.review_assignment_id;
    trigger: reviewFields.trigger;
    application_id: reviewFields.application_id;
    reviewer_id: reviewFields.reviewer_id;
    level: reviewFields.level;
    is_last_level: reviewFields.is_last_level;

}

export namespace review_assignmentFields {
    export type id = number;
    export type assigner_id = number | null;
    export type reviewer_id = number | null;
    export type organisation_id = number | null;
    export type stage_id = number | null;
    export type stage_number = number | null;
    export type status = review_assignment_status;
    export type application_id = number | null;
    export type template_section_restrictions = Array<string> | null;
    export type trigger = trigger | null;
    export type time_created = Date | null;
    export type level = number | null;
    export type is_last_level = boolean | null;

}

export interface review_assignment {
    id: review_assignmentFields.id;
    assigner_id: review_assignmentFields.assigner_id;
    reviewer_id: review_assignmentFields.reviewer_id;
    organisation_id: review_assignmentFields.organisation_id;
    stage_id: review_assignmentFields.stage_id;
    stage_number: review_assignmentFields.stage_number;
    status: review_assignmentFields.status;
    application_id: review_assignmentFields.application_id;
    template_section_restrictions: review_assignmentFields.template_section_restrictions;
    trigger: review_assignmentFields.trigger;
    time_created: review_assignmentFields.time_created;
    level: review_assignmentFields.level;
    is_last_level: review_assignmentFields.is_last_level;

}

export namespace review_decisionFields {
    export type id = number;
    export type review_id = number | null;
    export type review_decision = decision | null;
    export type comment = string | null;
    export type time_created = Date | null;

}

export interface review_decision {
    id: review_decisionFields.id;
    review_id: review_decisionFields.review_id;
    review_decision: review_decisionFields.review_decision;
    comment: review_decisionFields.comment;
    time_created: review_decisionFields.time_created;

}

export namespace review_question_assignmentFields {
    export type id = number;
    export type template_element_id = number | null;
    export type review_assignment_id = number | null;

}

export interface review_question_assignment {
    id: review_question_assignmentFields.id;
    template_element_id: review_question_assignmentFields.template_element_id;
    review_assignment_id: review_question_assignmentFields.review_assignment_id;

}

export namespace review_responseFields {
    export type id = number;
    export type comment = string | null;
    export type decision = review_response_decision | null;
    export type review_question_assignment_id = number | null;
    export type application_response_id = number | null;
    export type review_response_link_id = number | null;
    export type review_id = number | null;
    export type time_created = Date | null;
    export type status = review_response_status | null;

}

export interface review_response {
    id: review_responseFields.id;
    comment: review_responseFields.comment;
    decision: review_responseFields.decision;
    review_question_assignment_id: review_responseFields.review_question_assignment_id;
    application_response_id: review_responseFields.application_response_id;
    review_response_link_id: review_responseFields.review_response_link_id;
    review_id: review_responseFields.review_id;
    time_created: review_responseFields.time_created;
    status: review_responseFields.status;

}

export namespace review_status_historyFields {
    export type id = number;
    export type review_id = number | null;
    export type status = review_status | null;
    export type time_created = Date | null;
    export type is_current = boolean | null;

}

export interface review_status_history {
    id: review_status_historyFields.id;
    review_id: review_status_historyFields.review_id;
    status: review_status_historyFields.status;
    time_created: review_status_historyFields.time_created;
    is_current: review_status_historyFields.is_current;

}

export namespace templateFields {
    export type id = number;
    export type name = string | null;
    export type code = string;
    export type is_linear = boolean | null;
    export type start_message = Object | null;
    export type status = template_status | null;
    export type submission_message = Object | null;
    export type version_timestamp = Date | null;

}

export interface template {
    id: templateFields.id;
    name: templateFields.name;
    code: templateFields.code;
    is_linear: templateFields.is_linear;
    start_message: templateFields.start_message;
    status: templateFields.status;
    submission_message: templateFields.submission_message;
    version_timestamp: templateFields.version_timestamp;

}

export namespace template_actionFields {
    export type id = number;
    export type template_id = number | null;
    export type action_code = string | null;
    export type trigger = trigger | null;
    export type sequence = number | null;
    export type condition = Object | null;
    export type parameter_queries = Object | null;

}

export interface template_action {
    id: template_actionFields.id;
    template_id: template_actionFields.template_id;
    action_code: template_actionFields.action_code;
    trigger: template_actionFields.trigger;
    sequence: template_actionFields.sequence;
    condition: template_actionFields.condition;
    parameter_queries: template_actionFields.parameter_queries;

}

export namespace template_elementFields {
    export type id = number;
    export type section_id = number | null;
    export type code = string;
    export type index = number | null;
    export type title = string | null;
    export type category = template_element_category | null;
    export type element_type_plugin_code = string | null;
    export type visibility_condition = Object | null;
    export type is_required = Object | null;
    export type is_editable = Object | null;
    export type validation = Object | null;
    export type validation_message = string | null;
    export type parameters = Object | null;

}

export interface template_element {
    id: template_elementFields.id;
    section_id: template_elementFields.section_id;
    code: template_elementFields.code;
    index: template_elementFields.index;
    title: template_elementFields.title;
    category: template_elementFields.category;
    element_type_plugin_code: template_elementFields.element_type_plugin_code;
    visibility_condition: template_elementFields.visibility_condition;
    is_required: template_elementFields.is_required;
    is_editable: template_elementFields.is_editable;
    validation: template_elementFields.validation;
    validation_message: template_elementFields.validation_message;
    parameters: template_elementFields.parameters;

}

export namespace template_permissionFields {
    export type id = number;
    export type permission_name_id = number | null;
    export type template_id = number | null;
    export type stage_number = number | null;
    export type level = number | null;
    export type restrictions = Object | null;

}

export interface template_permission {
    id: template_permissionFields.id;
    permission_name_id: template_permissionFields.permission_name_id;
    template_id: template_permissionFields.template_id;
    stage_number: template_permissionFields.stage_number;
    level: template_permissionFields.level;
    restrictions: template_permissionFields.restrictions;

}

export namespace template_sectionFields {
    export type id = number;
    export type template_id = number | null;
    export type title = string | null;
    export type code = string | null;
    export type index = number | null;

}

export interface template_section {
    id: template_sectionFields.id;
    template_id: template_sectionFields.template_id;
    title: template_sectionFields.title;
    code: template_sectionFields.code;
    index: template_sectionFields.index;

}

export namespace template_stageFields {
    export type id = number;
    export type number_ = number | null;
    export type title = string | null;
    export type description = string | null;
    export type template_id = number | null;

}

export interface template_stage {
    id: template_stageFields.id;
    number: template_stageFields.number_;
    title: template_stageFields.title;
    description: template_stageFields.description;
    template_id: template_stageFields.template_id;

}

export namespace trigger_queueFields {
    export type id = number;
    export type trigger_type = trigger | null;
    export type table = string | null;
    export type record_id = number | null;
    export type timestamp = Date | null;
    export type status = trigger_queue_status | null;
    export type log = Object | null;

}

export interface trigger_queue {
    id: trigger_queueFields.id;
    trigger_type: trigger_queueFields.trigger_type;
    table: trigger_queueFields.table;
    record_id: trigger_queueFields.record_id;
    timestamp: trigger_queueFields.timestamp;
    status: trigger_queueFields.status;
    log: trigger_queueFields.log;

}

export namespace userFields {
    export type id = number;
    export type first_name = string | null;
    export type last_name = string | null;
    export type username = string | null;
    export type email = string | null;
    export type date_of_birth = Date | null;
    export type password_hash = string | null;

}

export interface user {
    id: userFields.id;
    first_name: userFields.first_name;
    last_name: userFields.last_name;
    username: userFields.username;
    email: userFields.email;
    date_of_birth: userFields.date_of_birth;
    password_hash: userFields.password_hash;

}

export namespace user_org_joinFields {
    export type user_id = number | null;
    export type username = string | null;
    export type first_name = string | null;
    export type last_name = string | null;
    export type email = string | null;
    export type date_of_birth = Date | null;
    export type password_hash = string | null;
    export type org_id = number | null;
    export type org_name = string | null;
    export type user_role = string | null;
    export type licence_number = string | null;
    export type address = string | null;

}

export interface user_org_join {
    user_id: user_org_joinFields.user_id;
    username: user_org_joinFields.username;
    first_name: user_org_joinFields.first_name;
    last_name: user_org_joinFields.last_name;
    email: user_org_joinFields.email;
    date_of_birth: user_org_joinFields.date_of_birth;
    password_hash: user_org_joinFields.password_hash;
    org_id: user_org_joinFields.org_id;
    org_name: user_org_joinFields.org_name;
    user_role: user_org_joinFields.user_role;
    licence_number: user_org_joinFields.licence_number;
    address: user_org_joinFields.address;

}

export namespace user_organisationFields {
    export type id = number;
    export type user_id = number | null;
    export type organisation_id = number | null;
    export type user_role = string | null;

}

export interface user_organisation {
    id: user_organisationFields.id;
    user_id: user_organisationFields.user_id;
    organisation_id: user_organisationFields.organisation_id;
    user_role: user_organisationFields.user_role;

}
